### ISSUE TITLE
您好，我尝试安装了torch-1.4.0+cpu和torch-1.4.0两个版本，依然报错

### ISSUE THREAD

**Issue by 17702513221** [yeyupiaoling/MASR#4]
libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by 17702513221** [comment]
python3 train.py 
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from warpctc_pytorch import CTCLoss
  File "/usr/local/lib/python3.6/dist-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 6, in <module>
    from ._warp_ctc import *  # noqa
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by yeyupiaoling** [comment]
@17702513221 很明显你的Pytorch没有安装成功，可以试试使用anaconda安装
```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```

**Comment by 17702513221** [comment]
好了，谢谢
