### ISSUE TITLE
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by dianxin556** [yeyupiaoling/MASR#62]
Traceback (most recent call last):
  File "/workspace/MASR/infer_server.py", line 55, in <module>
    pun_model_dir=args.pun_model_dir)
  File "/workspace/MASR/masr/predict.py", line 87, in __init__
    use_gpu=self.use_gpu)
  File "/workspace/MASR/masr/infer_utils/inference_predictor.py", line 34, in __init__
    self.predictor = torch.jit.load(model_path)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found
![image](https://user-images.githubusercontent.com/6285399/233823940-0080166e-83d7-4339-8862-2d0364fa0866.png)

**Comment by yeyupiaoling** [comment]
你没有导出模型吧？

**Comment by dfmjndm** [comment]
同样的问题，使用的是他人预训练的模型

**Comment by yeyupiaoling** [comment]
不是这个项目的模型用不了的
