### ISSUE TITLE
在train.py运行开始时发生如下报错

### ISSUE THREAD

**Issue by Isaiah-pq** [yeyupiaoling/MASR#65]
/root/miniconda3/envs/MASR/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from masr.trainer import MASRTrainer
  File "/workspace/MASR-develop/masr/trainer.py", line 20, in <module>
    from masr.data_utils.featurizer.audio_featurizer import AudioFeaturizer
  File "/workspace/MASR-develop/masr/data_utils/featurizer/audio_featurizer.py", line 5, in <module>
    from masr.data_utils.audio import AudioSegment
  File "/workspace/MASR-develop/masr/data_utils/audio.py", line 8, in <module>
    import soundfile
  File "/root/miniconda3/envs/MASR/lib/python3.8/site-packages/soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
  File "/root/miniconda3/envs/MASR/lib/python3.8/site-packages/_soundfile.py", line 2, in <module>
    import _cffi_backend
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

请问怎么解决呀，python包都按照要求装了

**Comment by yeyupiaoling** [comment]
卸载soundfile 重装

**Comment by Isaiah-pq** [comment]
还是有同样的报错
soundfile版本是0.12.1 卸了后重装还是同样版本

**Comment by yeyupiaoling** [comment]
sudo apt-get install libsndfile1

**Comment by yeyupiaoling** [comment]
这个试试，卸载重装

**Comment by Isaiah-pq** [comment]
谢谢~重装了后能跑了！
