### ISSUE TITLE
运行train.py报错

### ISSUE THREAD

**Issue by happywch** [yeyupiaoling/MASR#69]
Traceback (most recent call last):                                                                                  'feature', 'params': {'max_t': 30, 'num_t_sub': 3}, 'prob': 1.0}
  File "c:\Users\ww\Desktop\MASR-release-2.3.x\train.py", line 26, in <module>
    trainer.train(save_model_path=args.save_model_path,
  File "c:\Users\ww\Desktop\MASR-release-2.3.x\masr\trainer.py", line 482, in train
    self.__setup_dataloader(augment_conf_path=augment_conf_path, is_train=True)
  File "c:\Users\ww\Desktop\MASR-release-2.3.x\masr\trainer.py", line 99, in __setup_dataloader
    self.train_loader = DataLoader(dataset=self.train_dataset,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\CBVR\Lib\site-packages\torch\utils\data\dataloader.py", line 245, in __init__
    raise ValueError('prefetch_factor option could only be specified in multiprocessing.'
ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing, otherwise set prefetch_factor to None.   

报错如上，在create_data.py 时并没有使用python create_data.py --is_merge_audio=True来生成二进制，是这个原因引起的吗。目前已经在dataset下生成manifest.test、manifest.train、mean_istd
.json、vocabulary.txt都已经生成并且都正常

**Comment by yeyupiaoling** [comment]
这个是最新版本pytorch的原因，代码已经修复了。
