### ISSUE TITLE
这个是不是不能用于cuda为11.4的

### ISSUE THREAD

**Issue by ghost** [yeyupiaoling/MASR#74]

**Comment by yeyupiaoling** [comment]
torch支持就行

**Comment by ghost** [comment]
> torch支持就行
(masr) nvidia@tegra-ubuntu:~/MASR$ python create_data.py 
Traceback (most recent call last):
  File "/home/nvidia/MASR/create_data.py", line 4, in <module>
    from masr.trainer import MASRTrainer
  File "/home/nvidia/MASR/masr/trainer.py", line 21, in <module>
    from masr.data_utils.featurizer.audio_featurizer import AudioFeaturizer
  File "/home/nvidia/MASR/masr/data_utils/featurizer/audio_featurizer.py", line 3, in <module>
    from torchaudio.compliance.kaldi import mfcc, fbank
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torch/_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv

**Comment by ghost** [comment]
我这Ubuntu是20.04的

**Comment by yeyupiaoling** [comment]
看起来是torchaudio动态库的问题，可以卸载重装试试，用conda安装，我文档给出了安装命令
