### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by zzx856** [yeyupiaoling/MASR#77]
使用命令python infer_path.py --wav_path=./dataset/test_long.wav --is_long_audio=True
模型为自己训练的模型，第1批次
报错内容：
初始化解码器...
language model: model path = lm/zh_giga.no_cna_cmn.prune01244.klm, is_character_based = True, max_order = 5, dict_size = 0
初始化解码器完成!
======================================================================
[2024-12-16 18:02:44 INFO   ] inference_predictor:__init__:42 - 已加载模型：models/conformer_streaming_fbank/inference.pt
[2024-12-16 18:02:45 INFO   ] vad_predictor:__init__:52 - 成功初始化VAD推理工具
[2024-12-16 18:02:47 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
C:\Downloads\MASR-release-2.3.x\MASR-release-2.3.x\masr\infer_utils\inference_predictor.py:63: UserWarning: FALLBACK path has been taken inside: torch::jit::fuser::cuda::runCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
 (Triggered internally at ..\third_party\nvfuser\csrc\manager.cpp:340.)
  output_data = self.predictor.get_encoder_out(speech=audio_data, speech_lengths=audio_len)

[2024-12-16 18:03:00 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:00 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:00 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:00 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:00 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:00 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:01 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:01 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:01 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:01 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:01 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:02 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:02 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:02 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:02 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:02 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:03 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:03 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:03 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:03 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:04 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:04 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
[2024-12-16 18:03:04 INFO   ] predict:predict_long:225 - 长语音识别片段结果：
Traceback (most recent call last):
  File "C:\Downloads\MASR-release-2.3.x\MASR-release-2.3.x\infer_path.py", line 77, in <module>
    predict_long_audio()
  File "C:\Downloads\MASR-release-2.3.x\MASR-release-2.3.x\infer_path.py", line 42, in predict_long_audio
    result = predictor.predict_long(audio_data=args.wav_path, use_pun=args.use_pun, is_itn=args.is_itn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Downloads\MASR-release-2.3.x\MASR-release-2.3.x\masr\predict.py", line 226, in predict_long
    if texts[0] == '，': texts = texts[1:]
       ~~~~~^^^
IndexError: string index out of range
请问大佬是什么原因？

**Comment by yeyupiaoling** [comment]
@zzx856 这个错误是因为你没有识别到结果，导致在添加标点符号的时候出了问题。这个也可以说是一个小bug吧，因为没有判空。

**Comment by zzx856** [comment]
谢谢，已解决
